//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDCANCEL2                       3
#define IDOK2                           3
#define IDM_MENU                        100
#define IDM_HEADER_SORT_UNSORTED        101
#define IDM_HEADER_SORT_NAME            102
#define IDM_HEADER_SORT_EXTENSION       103
#define IDM_HEADER_SORT_SIZE            104
#define IDM_HEADER_SORT_TIME_CREATE     105
#define IDM_HEADER_SORT_TIME_ACCESS     106
#define IDM_HEADER_SORT_TIME_WRITE      107
#define IDM_HEADER_SORT_GROUP           108
#define IDM_HEADER_SORT_REVERSE         109
#define IDM_HEADER_SORT_SEPARATOR       110
#define IDM_SELECTION_SELECT_ALL        111
#define IDM_SELECTION_SELECT_NONE       112
#define IDM_SELECTION_SELECT_INVERSE    113
#define IDM_SELECTION_SELECT_FILTER     114
#define IDM_SELECTION_SELECT_FILTER_INV 115
#define IDM_DRIVE_0                     116
#define IDM_DRIVE_63                    178
#define IDM_DRIVE_SEPARATOR             179
#define IDM_DRIVE_ROOT                  180
#define IDM_DRIVE_BM_0                  182
#define IDM_DRIVE_BM_63                 245
#define IDM_DRIVE_BM_ADD                246
#define IDM_DRIVE_BM_EDIT               247
#define IDM_HEADER_VIEW_1C              248
#define IDM_HEADER_VIEW_2C              249
#define IDM_HEADER_VIEW_3C              250
#define IDM_HEADER_VIEW_BRIEF           251
#define IDM_HEADER_VIEW_MEDIUM          252
#define IDM_HEADER_VIEW_FULL            253
#define IDM_HEADER_OPEN_OPPOSITE        255
#define IDM_EMPTY                       256
#define IDM_FILE_MENU_SEPARATOR         257
#define IDM_FILE_MENU_OPENWITH          258
#define IDM_FILE_MENU_VIEW              259
#define IDM_FILE_MENU_PROPERTIES        260
#define IDM_FILE_MENU_OPPOSITE          261
#define IDM_FILE_MENU_COPYMOVE          262
#define IDM_FILE_MENU_RENAME            263
#define IDM_FILE_MENU_DELETE            264
#define IDM_FILE_MENU_SHORTCUT          265
#define IDM_FILE_MENU_MARK              268
#define IDM_FILE_MENU_CLEAR             269
#define IDM_FILE_MENU_CLEAR_ALL         270
#define IDM_FILE_MENU_MARK_ALL          271
#define IDM_FILE_MENU_SEND_IR           272
#define IDM_FILE_MENU_SEND_BT           273
#define IDM_FILE_MENU_BOOKMARK          274
#define IDM_FILE_MENU_OPEN              275
#define IDM_FILE_MENU_OPEN_0            276
#define IDM_FILE_MENU_OPEN_1            277
#define IDM_FILE_MENU_OPEN_2            278
#define IDM_FILE_MENU_OPEN_3            279
#define IDM_FILE_MENU_OPEN_4            280
#define IDM_FILE_MENU_OPEN_5            281
#define IDM_FILE_MENU_OPEN_6            282
#define IDM_FILE_MENU_OPEN_7            283
#define IDM_FILE_MENU_OPEN_8            284
#define IDM_FILE_MENU_OPEN_9            285
#define IDM_FILE_MENU_OPEN_10           286
#define IDM_MISC_REGISTER               287
#define IDM_MISC_EXIT                   288
#define IDM_MISC_ABOUT                  289
#define IDM_MISC_FULLSCREEN             290
#define IDM_MISC_OPTIONS                291
#define IDM_SK1_SK2                     292
#define IDR_SK1_SK2                     293
#define IDM_MISC_MINIMIZE               294
#define IDM_NEWMENU_0                   295
#define IDM_NEWMENU_64                  359
#define IDM_HEADER_OPEN                 360
#define IDM_FILE_MENU_RUNPARAMS         361
#define IDM_BOOKMARKS                   362
#define IDM_FILE_MENU_COPYCLIP          363
#define IDM_FILE_MENU_CUTCLIP           364
#define IDM_FILE_MENU_PASTECLIP         365
#define IDM_HEADER_SORT_SIZE_PACKED     366
#define IDM_DRIVE_PLUGIN_0              367
#define IDM_DRIVE_PLUGIN_63             430
#define IDM_FILE_MENU_PLUGIN_0			431
#define IDM_FILE_MENU_PLUGIN_63			494
#define IDC_DUMMY                       1001
#define IDC_SELECTION_CHECK             1002
#define IDC_COPYMOVE_FILES              1004
#define IDC_DELETE_FILES                1005
#define IDC_NEWDOC                      1007
#define IDC_FIND                        1008
#define IDC_TOOLBAR                     1009
#define IDC_OPTIONS                     1010
#define IDC_EXIT                        1011
#define IDS_CAP_CANCEL                  1046
#define IDS_CAP_NAVIGATE                1047
#define IDS_NULL                        1048
#define IDC_COPY_TEXT                   1053
#define IDS_CAP_OK                      1059
#define IDC_TOTAL_PROGRESS              1064
#define IDC_FILE_PROGRESS               1065
#define IDC_SOURCE_TEXT                 1066
#define IDC_FULLSCREEN                  1066
#define IDC_DEST_TEXT                   1067
#define IDC_FASTNAV                     1067
#define IDC_TOTAL_PERCENT               1068
#define IDC_FILE_PERCENT                1069
#define IDC_TOTAL_SIZE                  1070
#define IDC_RENAME                      1072
#define IDC_MISC                        1073
#define IDC_DELETE_FILE                 1074
#define IDC_SEPARATOR                   1075
#define IDC_DIRECTORIES                 1077
#define IDC_FONT_NAME                   1081
#define IDC_SCHEME                      1082
#define IDC_FONT_BOLD                   1083
#define IDC_FONT_SMOOTH                 1084
#define IDC_VIEW                        1084
#define IDC_FONT_SIZE                   1085
#define IDC_SPLITTER_HEIGHT             1086
#define IDC_REFRESH                     1086
#define IDC_FONT_SIZE_SPIN              1087
#define ID_BUTTON1087                   1087
#define IDC_PROPERTIES                  1087
#define IDC_SPLITTER_HEIGHT_SPIN        1088
#define IDC_BORDER                      1088
#define IDC_APPLY                       1089
#define IDC_FILE1                       1090
#define IDC_FILE2                       1091
#define IDC_SHORTCUT                    1092
#define IDC_LEFT_VIEW                   1094
#define ID_1_SUB1                       1094
#define IDC_LEFT_SORT                   1095
#define ID_2_SUB2                       1095
#define IDC_LEFT_REVERSE                1096
#define IDC_ICON_BOTTOM                 1097
#define IDC_LAYOUT                      1097
#define IDC_SHOW_SYSTEM                 1098
#define IDC_ICON_SHORT                  1099
#define IDC_SHOW_SYSTEM2                1099
#define IDC_FILTERDIRS                  1099
#define IDC_RIGHT_VIEW                  1100
#define IDC_ICON_MID                    1100
#define IDC_RIGHT_SORT                  1101
#define IDC_ICON_FULL                   1101
#define IDC_EXT_SHORT                   1102
#define IDC_EXT_MID                     1103
#define IDC_COMMAND_LIST                1103
#define IDC_EXT_FULL                    1104
#define IDC_BTN_ASSIGN                  1104
#define IDC_SHOW_HIDDEN                 1105
#define IDC_BTN_CLEAR                   1105
#define IDC_BTN_ASSIGN2                 1105
#define IDC_SHOW_HIDDEN2                1106
#define IDC_SHOW_ROM                    1106
#define IDC_DATE_BOTTOM                 1107
#define IDC_ICON_BOTTOM3                1109
#define IDC_SIZE_BOTTOM                 1109
#define IDC_TIME_BOTTOM                 1109
#define IDC_SLIDER_WIDTH                1110
#define IDC_SLIDER_WIDTH_SPIN           1111
#define IDC_RIGHT_REVERSE               1113
#define IDC_CURSOR_BAR                  1114
#define IDC_RIGHT_REVERSE2              1114
#define IDC_REGISTER                    1115
#define IDC_HEADER                      1116
#define IDC_LATER                       1116
#define IDC_FIND_ATTRIBUTES_CHECK       1118
#define IDC_SEARCH_FOR_FOLDERS          1118
#define IDC_FIND_SIZE_GREATER_CHK       1118
#define IDC_REGISTER2                   1118
#define IDC_FIND_TEXT                   1119
#define IDC_FIND_ARCHIVE                1119
#define IDC_FIND_SIZE_LESS_CHK          1119
#define IDC_FIND_READONLY               1120
#define IDC_SEARCH_SUBFOLDERS           1120
#define IDC_FIND_WHOLE_CHECK            1121
#define IDC_FIND_HIDDEN                 1121
#define IDC_FIND_CURFOLDER              1122
#define IDC_FIND_SIZE_COMBO_1           1122
#define IDC_FIND_SYSTEM                 1122
#define IDC_FIND_ROOT                   1123
#define IDC_FIND_SIZE_COMBO_2           1123
#define IDC_FIND_ROM                    1123
#define IDC_FIND_SELFOLDER              1124
#define IDC_FIND_OLDER_CHECK            1124
#define IDC_FIND_DATE_OLDER             1125
#define IDC_BM_NAME                     1125
#define IDC_REQ_CODE                    1125
#define IDC_FIND_DATE_OLDER_COMBO       1126
#define IDC_KEY_CODE                    1126
#define IDC_FIND_DATE_CHECK             1127
#define IDC_FIND_DATE_TYPE              1128
#define IDC_DATETIMEPICKER1             1129
#define IDC_DATETIMEPICKER2             1130
#define IDC_FIND_MASK                   1130
#define IDC_FIND_TEXT_CHECK             1131
#define IDC_FIND_CASE_CHECK             1132
#define IDC_FIND_SIZE1                  1133
#define IDC_FIND_SIZE2                  1134
#define IDC_FIND_NUMFILES               1134
#define IDC_FIND_FILE_LIST              1135
#define IDC_ORIGINAL                    1141
#define IDC_FILE_ICON                   1142
#define IDC_CURRENT                     1142
#define IDC_FILENAME                    1143
#define IDC_TYPE                        1144
#define IDC_FILENAME_STATIC             1145
#define IDC_TYPE2                       1145
#define IDC_SORT                        1145
#define IDC_LOCATION                    1148
#define IDC_CONTAINS                    1149
#define IDC_FILE_SIZE                   1150
#define IDC_TIME_MODIFY                 1151
#define IDC_TIME_CREATE                 1151
#define IDC_DATE_MODIFY                 1152
#define IDC_DATE_CREATE                 1152
#define IDC_BM_PATH                     1153
#define IDC_TOTAL_SPACE                 1153
#define IDC_TIME_ACCESS                 1153
#define IDC_BM_LIST                     1154
#define IDC_FREE_SPACE                  1154
#define IDC_DATE_ACCESS                 1154
#define IDC_TIME_WRITE                  1155
#define IDC_BM_DELETE                   1156
#define IDC_DATE_WRITE                  1156
#define IDC_FILTER_HEADER               1157
#define IDC_BM_UP                       1157
#define IDC_BM_UP2                      1158
#define IDC_ICON_ONE                    1159
#define IDC_BM_DOWN                     1159
#define IDC_EXT_ONE                     1160
#define IDC_VERSION                     1160
#define IDC_BM_ADD                      1160
#define IDC_REQ_CODE_TEXT               1161
#define IDC_BM_EDIT                     1161
#define IDC_PRODUCT_KEY_TEXT            1162
#define IDC_VERSION_NUMBER              1164
#define IDC_ICON_APP                    1165
#define IDC_COMPANY                     1166
#define IDC_ERROR                       1167
#define IDC_OPERATION                   1169
#define IDC_CONF_COPY_OVER              1171
#define IDC_CONF_MOVE_OVER              1172
#define IDC_OVER                        1173
#define IDC_CONF_MOVE_OVER2             1173
#define IDC_OVER_ALL                    1174
#define IDC_CONF_HISTORY                1174
#define IDC_OVER3                       1174
#define IDC_SKIP_ALL                    1176
#define IDC_OVER2                       1178
#define IDC_LINK                        1179
#define IDC_CONF_EXIT                   1180
#define IDC_LINK2                       1180
#define IDC_LINK3                       1181
#define IDC_DAYS_LEFT                   1182
#define IDC_LINK4                       1182
#define IDC_CONTAINS_STATIC             1183
#define IDC_TITLE                       1186
#define IDC_COPY_COMBO                  1187
#define IDC_TITLE2                      1187
#define IDC_SEARCH                      1187
#define IDC_ACCESS_STATIC               1187
#define IDC_ACTION                      1187
#define IDC_COPY                        1188
#define IDC_TITLE3                      1188
#define IDC_MODIFY_STATIC               1188
#define IDC_MOVE                        1189
#define IDC_FOLDER_COMBO                1190
#define IDC_COPY_SHORTCUT               1190
#define IDC_COPY_SHORTCUT2              1191
#define IDC_RENAME_COMBO                1192
#define IDC_TEXT                        1192
#define IDC_RENAME_TEXT                 1193
#define IDC_TEXT2                       1193
#define IDC_EDIT1                       1194
#define IDC_PWD1                        1194
#define IDC_VIEWER                      1194
#define IDC_PERIOD                      1194
#define IDC_EXE                         1194
#define IDC_TARGET                      1194
#define IDC_FILTER_COMBO                1195
#define IDC_ALG_COMBO                   1195
#define IDC_MAXFILES                    1195
#define IDC_PWD2                        1196
#define IDC_CHECK1                      1197
#define IDC_DELETE_CHECK                1197
#define IDC_FULLSCREEN_CHECK            1197
#define IDC_ALWAYS                      1197
#define IDC_AUTOREFRESH                 1197
#define IDC_DIR                         1197
#define IDC_LONG1                       1197
#define IDC_FORCE                       1197
#define IDC_BLOCK                       1197
#define IDC_FOLDERS_CHECK               1197
#define IDC_COMBO1                      1198
#define IDC_ORIENT_COMBO                1198
#define IDC_DEST_COMBO                  1198
#define IDC_LONG2                       1198
#define IDC_VIEW_COMBO                  1198
#define IDC_BM_DRIVES                   1199
#define IDC_FULLSCREEN_CHECK2           1199
#define IDC_SLIDER_LEFT_CHECK           1199
#define IDC_ALWAYS2                     1199
#define IDC_QUOTES                      1199
#define IDC_LONG3                       1199
#define IDC_BM_ICONS                    1200
#define IDC_WM5_TOOLBAR                 1200
#define IDC_2ND_TOOLBAR                 1201
#define IDC_NAME                        1202
#define IDC_DOUBLE                      1202
#define IDC_PARAMS                      1203
#define IDC_PATH                        1203
#define IDC_WM5_HIDE_TOOLBAR            1204
#define IDC_EDIT                        1205
#define IDC_NUM_ENC_TEXT                1206
#define IDC_TOTAL                       1207
#define IDC_PROCESSED                   1208
#define IDC_FILE_LIST                   1209
#define IDC_ALG_TEXT                    1211
#define IDC_BROWSE                      1212
#define IDC_LIST                        1213
#define IDC_SK1                         1214
#define IDC_SK2                         1215
#define IDC_LANGUAGE_STATIC             1215
#define IDC_SWITCH_PANES                1216
#define IDC_FILEINFO_STATIC             1216
#define IDC_MAXIMIZE_PANE               1217
#define IDC_CREATE_STATIC               1217
#define IDC_SAME_AS_OPPOSITE            1218
#define IDC_LONG_STATIC                 1218
#define IDS_CAP_SK1                     1219
#define IDC_PERIOD_STATIC               1219
#define IDS_CAP_SK2                     1220
#define IDC_MAX_STATIC                  1220
#define IDC_TO                          1221
#define IDC_FILENAME_EDIT               1221
#define IDC_FROM                        1222
#define IDC_FILENAME_EDIT2              1222
#define IDC_TREE                        1222
#define IDC_PASSWORD                    1223
#define IDC_NAME_EDIT                   1223
#define IDC_TREE2                       1223
#define IDC_TREE_OBJ                    1223
#define IDC_CONF_PASSWORD               1224
#define IDC_PATH_EDIT                   1224
#define IDC_NUM_FILES                   1224
#define IDC_NAME_EDIT2                  1224
#define IDC_NAME_STATIC                 1225
#define IDC_BUTTON1                     1225
#define IDC_ASSIGN1                     1225
#define IDC_OBJECT_STATIC               1226
#define IDC_BUTTON2                     1226
#define IDC_CLEAR1                      1226
#define IDC_DEST_STATIC                 1227
#define IDC_BUTTON3                     1227
#define IDC_CLEAR2                      1227
#define IDC_BUTTON4                     1228
#define IDC_ASSIGN2                     1228
#define IDC_FONT_STATIC                 1229
#define IDC_CLEAR3                      1229
#define IDC_SIZE_STATIC                 1230
#define IDC_ASSIGN3                     1230
#define IDC_SCHEME_STATIC               1231
#define IDC_LAYOUT_STATIC               1232
#define IDC_1ST_PANE_STATIC             1233
#define IDC_2ND_PANE_STATIC             1234
#define IDC_GROUP1                      1234
#define IDC_VIEW_STATIC1                1235
#define IDC_NAME1                       1235
#define IDC_SORT_STATIC1                1236
#define IDC_NAME2                       1236
#define IDC_TYPE_STATIC                 1236
#define IDC_VIEW_STATIC2                1237
#define IDC_GROUP2                      1237
#define IDC_SORT_STATIC                 1237
#define IDC_TREE_DEST                   1237
#define IDC_SORT_STATIC2                1238
#define IDC_NAME3                       1238
#define IDC_PARAMS_STATIC               1238
#define IDC_FILES_STATIC                1239
#define IDC_GROUP3                      1239
#define IDC_PARAMS_STATIC2              1239
#define IDC_EXE_STATIC                  1239
#define IDC_TARGET_STATIC               1239
#define IDC_MODES_STATIC                1240
#define IDC_1C_STATIC                   1241
#define IDC_2C_STATIC                   1242
#define IDC_3C_STATIC                   1243
#define IDC_D_STATIC                    1244
#define IDC_CONF_STATIC                 1245
#define IDC_VIEWER_STATIC               1246
#define IDC_ORIENT_STATIC               1247
#define IDC_SPLITTER_STATIC             1248
#define IDC_SLIDER_STATIC               1249
#define IDC_MASK_STATIC                 1250
#define IDC_AREA_STATIC                 1251
#define IDC_TIMEDATE_STATIC             1252
#define IDC_BETWEEN_STATIC              1253
#define IDC_LOCATION_STATIC             1254
#define IDC_ATTRIB_STATIC               1255
#define IDC_USED_SPACE_STATIC           1256
#define IDC_FREE_SPACE_STATIC           1257
#define IDC_TOTAL_SPACE_STATIC          1258
#define IDC_HOMEPAGE_STATIC             1259
#define IDC_PURCHASE_STATIC             1260
#define IDC_SUPPORT_STATIC              1261
#define IDC_REGISTER_STATIC             1262
#define IDC_NAG_STATIC                  1263
#define IDC_TOTAL_STATIC                1264
#define IDC_LANGUAGE_COMBO              1265
#define IDC_SEND                        1266
#define IDC_FOLDER_UP                   1267
#define IDC_LONGCUT                     1268
#define IDC_MKDIR                       1269
#define IDC_COPYCLIP                    1270
#define IDC_CUTCLIP                     1271
#define IDC_PASTECLIP                   1272
#define IDB_TOOLBAR                     2010
#define IDB_TOOLBAR2                    2011
#define IDB_TOOLBAR_VGA                 2012
#define TGA_TEST                        2013
#define IDD_SET_FILTER                  5006
#define IDM_FILTER_MENU                 5007
#define IDM_OK_CANCEL                   5007
#define IDD_COPYMOVE_FILES              5008
#define IDM_COPYMOVE_MENU               5013
#define IDB_MIDSIZE                     5014
#define IDB_MAXSIZE                     5015
#define IDB_DIRS                        5016
#define IDD_ERR_TWO_C                   5018
#define IDB_MAXSIZE_PRESSED             5019
#define IDB_MIDSIZE_PRESSED             5020
#define IDB_MAXSIZE_PRESSED_VGA         5021
#define IDB_MIDSIZE_PRESSED_VGA         5022
#define IDD_COPY_PROGRESS               5023
#define IDM_CANCEL                      5024
#define IDD_DELETE_FILES                5026
#define IDD_MKDIR                       5027
#define IDD_OPTIONS_STYLE               5028
#define IDD_OPTIONS_PANELS              5029
#define IDD_OPTIONS_VIEW                5030
#define IDD_OPTIONS_BUTTONS             5031
#define IDB_UP                          5032
#define IDD_OPTIONS_MISC                5033
#define IDD_OPTIONS_DISPLAY             5033
#define IDD_WAITBOX                     5035
#define IDD_FIND_FILES_1                5036
#define IDD_OPTIONS_BOOKMARKS           5037
#define IDD_FIND_FILES_2                5038
#define IDD_FIND_FILES_3                5039
#define IDM_FIND                        5040
#define IDD_FIND_RESULTS                5041
#define IDM_STOP                        5042
#define IDD_FILE_PROPERTIES0            5042
#define IDD_FILE_PROPERTIES1            5044
#define IDD_BM_ADD                      5045
#define IDD_BM_EDIT                     5046
#define IDD_FILE_PROPERTIES_CARD        5048
#define IDI_MULTI                       5050
#define IDD_ABOUT                       5052
#define IDD_REGISTER                    5053
#define IDD_ERR_TWO_R_C                 5056
#define IDB_DIRS_VGA                    5056
#define IDD_ERR_TWO_R_S_SA_C            5057
#define IDB_MAXSIZE_VGA                 5057
#define IDD_ERR_TWO_O_OA_S_SA_C         5058
#define IDB_MIDSIZE_VGA                 5058
#define IDD_ERR_ONE_C                   5059
#define IDB_UP_VGA                      5059
#define IDD_ERR_ONE_R_C                 5060
#define IDD_ERR_ONE_R_S_SA_C            5061
#define IDD_OPTIONS_CONFIRM             5062
#define IDD_ERR_ONE_O_OA_S_SA_C         5063
#define IDB_UP_PRESSED                  5064
#define IDD_RENAME_FILES                5065
#define IDB_UP_PRESSED_VGA              5066
#define IDD_WAITBOX_CANCEL              5067
#define IDB_DIRS_PRESSED                5067
#define IDB_DIRS_PRESSED_VGA            5068
#define IDD_ERROR_OK                    5069
#define IDD_ERROR_OK_CANCEL             5070
#define IDD_ERROR_YES_NO                5071
#define IDB_CHANGE_TO1                  5072
#define IDD_ENCRYPT                     5072
#define IDB_CHANGE_TO1_PRESSED          5073
#define IDD_ENCRYPT_PROGRESS            5073
#define IDB_CHANGE_TO2                  5074
#define IDB_CHANGE_TO2_PRESSED          5075
#define IDB_CHANGE_TO1_VGA              5076
#define IDB_CHANGE_TO1_PRESSED_VGA      5077
#define IDB_CHANGE_TO2_VGA              5078
#define IDB_CHANGE_TO2_PRESSED_VGA      5079
#define IDB_TOOLBAR2_VGA                5081
#define IDD_SHORTCUT                    5082
#define IDM_OK                          5083
#define IDD_CRYPT_RESULTS               5084
#define IDD_APPS                        5085
#define IDD_OPTIONS_EXTERNAL            5086
#define IDD_APP_SELECT                  5087
#define IDD_DECRYPT                     5088
#define IDD_OPTIONS_LANGUAGE            5089
#define IDD_FIND_DEVICE                 5090
#define IDD_SEND_PROGRESS               5091
#define IDD_OPTIONS_REFRESH             5092
#define IDD_OPTIONS_VIEW_1              5093
#define IDD_OPTIONS_VIEW_2              5094
#define IDD_OPTIONS_FILES               5094
#define IDD_DIR_TREE                    5095
#define IDD_BM_MOD                      5096
#define IDD_DELETE_PROGRESS             5097
#define IDD_BTN_ASSIGN                  5098
#define IDD_FILE_TREE                   5099
#define IDD_OPENDIR                     5100
#define IDD_CMN_EDIT                    5101
#define IDD_RUN_PARAMS                  5102
#define IDD_OPTIONS_VIEW2               5103
#define IDD_FILE_SHORTCUT               5104
#define IDD_ERR_ONE_S_SA_C            	5105
#define IDD_ERR_TWO_S_SA_C            	5106
#define IDB_SELECT                      5200
#define IDB_SELECT_VGA                  5201
#define IDB_PLUGIN                      5202
#define IDB_PLUGIN_VGA                  5203

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        5109
#define _APS_NEXT_COMMAND_VALUE         1096
#define _APS_NEXT_CONTROL_VALUE         1240
#define _APS_NEXT_SYMED_VALUE           5001
#endif
#endif
